com-pas/compas-open-scd

package-lock.json
src/compas/CompasChangeSet.ts
src/compas/CompasSaveTo.ts
src/compas/CompasScltypeRadiogroup.ts
src/wizard-dialog.ts

CheckValidity isn't available for Radio Buttons, so changed the method to just valid(), to check if we can save the SCL or leave the wizard open, if not all field are entered.

Check if save can be done

---

test/unit/wizard-dialog.test.ts

A suggestion for a test for the fix in this branch

test(wizard-dialog): add remove action tests

---

__snapshots__/compas-scl-list.md
__snapshots__/compas-scltype-list.md
__snapshots__/compas-scltype-radiogroup.md
__snapshots__/open-scd.md
public/js/plugins.js
src/compas-editors/CompasVersions.ts
src/compas-editors/foundation.ts
src/compas/CompasChangeSet.ts
src/compas/CompasSaveTo.ts
src/compas/CompasScl.ts
src/compas/CompasSclDataService.ts
src/compas/CompasScltypeList.ts
src/compas/CompasScltypeRadiogroup.ts
src/compas/CompasSetting.ts
src/compas/foundation.ts
src/savers/SaveToCompas.ts
src/translations/de.ts
src/translations/en.ts
test/unit/Plugging.test.ts
test/unit/compas/CompasSaveTo.test.ts
test/unit/compas/foundation.test.ts

This pull request contains 2 issues, adding a extra Editor to display the different versions for the loaded SCL.
And because the name should also be shown there also fixed showing the name when opening a SCL from CoMPAS.

Versions Editor + Show Name in stead of UUID

---

src/compas/CompasCimMappingService.ts
src/compas/CompasSclDataService.ts
test/unit/compas/CompasSclDataServiceResponses.ts

Signed-off-by: Dennis Labordus <dennis.labordus@alliander.com>

Changed Namespace URIs

---

__snapshots__/compas-save-to.md
src/compas-services/CompasSclDataService.ts
src/compas/CompasSaveTo.ts
src/translations/de.ts
src/translations/en.ts

Signed-off-by: Dennis Labordus <dennis.labordus@alliander.com>

Add TextField to add a comment when saving to CoMPAS.

---

src/compas-editors/CompasVersions.ts
src/compas-services/CompasCimMappingService.ts
src/compas-services/CompasSclDataService.ts
src/compas-services/CompasUserInfoService.ts
src/compas-services/foundation.ts
src/compas/CompasSaveTo.ts
src/compas/CompasScl.ts
src/compas/CompasScltypeList.ts
src/compas/CompasScltypeRadiogroup.ts
src/compas/foundation.ts
src/menu/CompasCimMapping.ts
src/translations/de.ts
src/translations/en.ts

Signed-off-by: Dennis Labordus <dennis.labordus@alliander.com>

Refactoring of error handling and processing of CoMPAS Service calls.

---

__snapshots__/compas-save-to.md
src/compas-editors/CompasVersions.ts
src/compas-services/foundation.ts
src/compas/CompasSaveTo.ts
src/compas/CompasScl.ts
src/compas/CompasScltypeList.ts
src/compas/CompasScltypeRadiogroup.ts
test/unit/compas/CompasSaveTo.test.ts

Also removed some of the Catch conditions. 
If uses in firstUpdated, adding a Log Event when it fails triggers the firstUpdated again, so infinite loop can happen :-)

Improve Check if Create or Update needs to be done

---

index.html
package.json
src/compas/CompasSession.ts
tsconfig.json
workbox-config.cjs

Created white list regex to only cache known urls.
Also changed the ping a little bit. the ping is done every minute doing the ping directly.
Also instruct the browser to send the credentials when retrieving the manifest.

Change Workbox config to excluded index.html and also compas url's.

---

public/js/plugins.js
src/Hosting.ts
src/compas-services/CompasValidatorService.ts
src/compas/CompasSettings.ts
src/translations/de.ts
src/translations/en.ts
src/validators/ValidateSchemaWithCompas.ts
test/integration/__snapshots__/open-scd.test.snap.js
test/unit/Plugging.test.ts

Added Validator Plugin to use CoMPAS SCL Validator Service.

---

public/js/plugins.js
src/menu/CompasSaveAs.ts
test/integration/__snapshots__/open-scd.test.snap.js

Added plugin to save project with a new name

---

src/compas-editors/CompasVersions.ts
src/compas-wizards/scl.ts
src/compas/private.ts
src/translations/de.ts
src/translations/en.ts
src/wizard-dialog.ts
src/wizards/wizard-library.ts
test/integration/compas-editors/CompasVersions.test.ts
test/integration/compas-editors/__snapshots__/CompasVersions.test.snap.js
test/testfiles/compas/compas-scl-private-missing-private.scd
test/testfiles/compas/compas-scl-private-missing-scl-name.scd
test/testfiles/compas/compas-scl-private-update-existing.scd
test/testfiles/compas/test-scd.cid
test/unit/compas-wizards/__snapshots__/scl.test.snap.js
test/unit/compas-wizards/scl.test.ts
test/unit/compas/private.test.ts

Added feature to update SCL Name in CoMPAS Private element.

---

src/compas-editors/CompasVersions.ts
test/integration/compas-editors/CompasVersions.test.ts
test/integration/compas-editors/__snapshots__/CompasVersions.test.snap.js

And small improvements.
closes #166

Fixed refresh after actions

---

Dockerfile
package-lock.json
package.json
public/conf/export-ied-parameters.json
public/conf/export-ied-params.json
public/js/plugins.js
src/menu/ExportIEDParams.ts
src/translations/de.ts
src/translations/en.ts
test/integration/__snapshots__/open-scd.test.snap.js
test/testfiles/menu/export-ied-params-no-ied.scd
test/testfiles/menu/export-ied-params.scd
test/unit/menu/ExportIEDParams.test.ts

New menu option to export IED Parameters to CSV File

---

src/Hosting.ts

Until final solution, we will just open the menu before clicking on the menu item.

Temporary fix for buttons on Landing Page

---

src/compas/CompasNsdoc.ts

Signed-off-by: Dennis Labordus <dennis.labordus@alliander.com>

Fix loading nsdoc files

---

src/compas-editors/CompasVersions.ts
src/plain-compare-list.ts
test/integration/compas-editors/__snapshots__/CompasVersions.test.snap.js
test/unit/__snapshots__/plain-compare-list.test.snap.js
test/unit/plain-compare-list.test.ts

Also fixed issue in Compare Component used from OpenSCD.
closes #193

Converted compare dialog to new component

---

.github/workflows/build-project.yml
.github/workflows/release-project.yml

fix: Increased Github Actions timeouts to 45 minutes

Increased timeouts to 45 mins

---

Dockerfile
public/nsdoc/README.md

Feat: Added nsdoc volume for Dockerfile

---

packages/compas-open-scd/src/compas-services/foundation.ts
packages/compas-open-scd/src/compas/CompasNsdoc.ts
packages/compas-open-scd/src/translations/de.ts
packages/compas-open-scd/src/translations/en.ts

fix: altered no nsdoc file warning message

---

packages/compas-open-scd/src/translations/de.ts
packages/compas-open-scd/src/translations/en.ts

* Add missing ti translations
* Fix plugins menu heading
closes #337, #336

fix: 104 plugin add missing ti translations

---

packages/compas-open-scd/src/translations/de.ts
packages/compas-open-scd/src/translations/en.ts

Sync translation files with open scd
closes #346

fix: 346 Compas open scd uses outdated translations

---

packages/plugins/src/menu/Export104.ts
packages/plugins/src/menu/export104/foundation.ts
packages/plugins/test/unit/menu/104Export/foundation.test.ts

- Change name format in 104 export
- Change mIOA/cIOA logic in 104 export

fix: export 104 csv feature update
