- src/compas-editors/CompasVersions.ts
- src/compas-services/foundation.ts
- src/compas/CompasExistsIn.ts
- test/unit/compas-services/foundation.test.ts
Function isNotFoundError no longer needed.
> When CoMPAS call fails react as if not in CoMPAS.

- src/Logging.ts
- src/Setting.ts
- src/compas-services/CompasValidatorService.ts
- src/compas/CompasNsdoc.ts
- src/menu/CompasSettings.ts
- src/translations/de.ts
- src/translations/en.ts
- test/integration/Setting.test.ts
- test/integration/__snapshots__/Setting.test.snap.js
- test/integration/__snapshots__/open-scd.test.snap.js
- test/integration/foundation.ts
- test/integration/open-scd.test.ts
- test/testfiles/nsdoc/IEC_61850-7-2.nsdoc
- test/testfiles/nsdoc/invalid.nsdoc
- test/testfiles/nsdoc/wrong-version.nsdoc
- test/testfiles/settingTest.nsdoc
- test/unit/Setting.test.ts
- test/unit/foundation/nsdoc.test.ts
When CoMPAS OpenSCD is loaded, just like retrieving the User Info, the NSDoc Info will be retrieve to determine if any NSDoc Files need to be loaded automatically.
closes #120
> Automatically Load NSDoc Files from SCL Validator Service

- Dockerfile
There is now a volume /etc/nginx/conf.d to make it possible to use your own NGiNX configuration if needed.
When using this volume some replacement of the default.conf needs to be there to configure a server on port 80.
If the volume isn't mapped there is the default.conf from NGiNX running on port 80 serving the directory /usr/share/nginx/html.
> Make it possible to replace NGiNX configuration through volume.

- src/compas-services/CompasValidatorService.ts
- src/compas/CompasNsdoc.ts
Because the response of the Service has changed, the processing of it also needed to be changed.
Related to https://github.com/com-pas/compas-scl-validator/pull/67
> Change processing of NSDOC File response

- src/compas-editors/CompasVersions.ts
- test/integration/compas-editors/CompasVersions.test.ts
- test/integration/compas-editors/__snapshots__/CompasVersions.test.snap.js
- test/unit/compas/CompasSclDataServiceResponses.ts
> On CoMPAS Version Tab show the information who/when/what per version

- src/validators/CompasValidateSchema.ts
- test/unit/validators/CompasValidateSchema.test.ts
> Changed processing of the new Validation Errors from Validator Service.

- src/validators/CompasValidateSchema.ts
- test/unit/validators/CompasValidateSchema.test.ts
Processing of the XSD Messages in the Validator Services added a new value 'ColumnNumber'. This new value is also displayed at the second line of the Diagnostic Dialog. Also the vale 'Linenumber' changed to 'LineNumber'.
> Processing of Column Number from Validation Messages

- src/compas/CompasOpen.ts
- src/compas/CompasSave.ts
- src/compas/CompasSclList.ts
- src/menu/CompasCompareIED.ts
- src/menu/CompasImportIEDs.ts
- src/menu/CompasMerge.ts
- src/menu/CompasOpen.ts
- src/menu/CompasSave.ts
- src/menu/CompasSaveAs.ts
- src/menu/CompasUpdateSubstation.ts
- src/oscd-filter-button.ts
- src/translations/de.ts
- src/translations/en.ts
- test/unit/__snapshots__/oscd-filter-button.test.snap.js
- test/unit/compas/CompasSclDataServiceResponses.ts
- test/unit/compas/CompasSclList.test.ts
- test/unit/compas/__snapshots__/CompasSclList.test.snap.js
- test/unit/menu/CompasOpen.test.ts
- test/unit/menu/__snapshots__/CompasOpen.test.snap.js
- test/unit/oscd-filter-button.test.ts
closes #184
- Also made small changes in the names of events
- And changed the way the Save Menu Items are closing the dialog, now through an event.
> Filter on labels when opening a SCL File from CoMPAS

- src/compas-editors/CompasVersions.ts
- src/compas-services/CompasSclDataService.ts
- src/compas-services/CompasValidatorService.ts
- src/compas-services/Websocket.ts
- src/compas-services/Websockets.ts
- src/compas/CompasExistsIn.ts
- src/compas/CompasOpen.ts
- src/compas/CompasSave.ts
- src/compas/CompasSclTypeList.ts
- src/compas/CompasSclTypeSelect.ts
- src/compas/CompasUploadVersion.ts
- src/validators/CompasValidateSchema.ts
@juancho0202 as already told a nicer version for using websocket.
The websocket function now returns a Promise<Document> like most rest calls are also doing after some response handling.
If something goes wrong a reject is done with the reason body as used in other places with rest calls.
This way the handling if websocket or rest should be used could be hidden in the service layer. 
Calling code doesn't know anymore.
Remark: I created a local container image and used the Docker Compose file and robot test script to validate the change.
> Refactor of Websocket wrapper to use promise.

- src/menu/CompasImportIEDs.ts
Fix for error found in compas-deployment:
`Error: locator.click: Error: strict mode violation: "mwc-dialog#compas-open-dlg > compas-open mwc-button[label="Open file..."] button" resolved to 2 elements:
1) <button id="button" class="mdc-button  " aria-label="Ope…>…</button> aka playwright.$("oscd-plugin8377febe1fad1914 [aria-label="Open file\.\.\."]")
2) <button id="button" class="mdc-button  " aria-label="Ope…>…</button> aka playwright.$("oscd-pluginb15ea127292dd242 [aria-label="Open file\.\.\."]")
`
> fix: making importIEDS dialog's id unique

- README.md
- RELEASING.md
- UPDATING.md
> docs: Release guide for this fork  

- src/compas-editors/autogen-substation.ts
- src/translations/de.ts
- src/translations/en.ts
> fix: autogen bugfix and multistation support

- src/Hosting.ts
- src/compas/CompasUserInfo.ts
- src/compas/foundation.ts
- src/foundation.ts
- test/integration/compas/foundation.test.ts
> Move user info to compas foundation

- packages/compas-open-scd/src/addons/CompasSession.ts
- packages/compas-open-scd/src/compas/CompasUserInfo.ts
- packages/compas-open-scd/src/open-scd.ts
> chore: Converts Compassing mixin into addon

- .github/workflows/automate-projects.yml
- packages/compas-open-scd/src/addons/CompasLayout.ts
* Fix username not displayed in header
closes #344
> Fix: Username is not displayed

- packages/compas-open-scd/public/js/plugins.js
- packages/compas-open-scd/src/translations/de.ts
- packages/compas-open-scd/src/translations/en.ts
- packages/plugins/src/menu/Export104.ts
- packages/plugins/src/menu/export104/foundation.ts
- packages/plugins/test/testfiles/export104/export104.scd
- packages/plugins/test/unit/menu/104Export/foundation.test.ts
* Add Menu Plugin which creates and downloads a CSV list of all 104 signals
closes #334
> feat: 104 Export menu plugin

- packages/compas-open-scd/workbox-config.cjs
The readme is for dev purposes only and is not used in the deployed version
> fix: Exclude nsdoc readme from service worker

- packages/compas-open-scd/workbox-config.cjs
* The `cacheId` is now dynamically set to include the package version, in order to create a unique cache for each release.
* Added a new caching rule for `package.json.proxy.js`. This ensures the app always fetches the latest version, so it can clear plugins from localStorage if the version changes.
* `clientsClaim` was added to ensure the new service worker takes control of all pages as soon as it's activated.
> fix: add version to cacheId + add package.json to SW caching

- .gitmodules
- packages/compas-open-scd/package.json
- packages/compas-open-scd/public/js/plugins.js
- packages/compas-open-scd/src/addons/CompasLayout.ts
- packages/compas-open-scd/src/menu/CompasOpen.ts
- packages/compas-open-scd/src/plugin-tag.ts
- packages/openscd/src/open-scd.ts
closes #377 
Extract menu item content from menu drawer, this also fixes the compas open bug, where we needed to open the menu to launch the open dialog
> fix: 377 add wizard plugin for substation designer

- packages/compas-open-scd/src/open-scd.ts
* Added event listener for `request-libdoc`, that is used in the `scl-bay-template` plugin (see: https://github.com/com-pas/scl-bay-template/pull/6)
> feature: add option to load libDoc

- packages/compas-open-scd/public/js/plugins.js
- packages/compas-open-scd/snowpack.config.mjs
> chore: update Communication Explorer plugin to version 0.0.32
